version: "2.3"
services:
  fgt-workspace:
    container_name: fgt-workspace
    networks:
      traceability-net:
        ipv4_address: 172.16.63.51
      qbn-net:
        ipv4_address: 172.16.16.51
    command: ["/bin/sh", "-c", "/fgt-workspace/docker/api/traceability/startup-script-bc.sh"]

networks:
  qbn-net:
    name: qbn-net
    external: true
