version: "2.3"
services:
  fgt-workspace:
    container_name: fgt-workspace
    networks:
      traceability-net:
        ipv4_address: 172.16.63.51
      qbn-net:
        ipv4_address: 172.16.16.51
    command: ["/bin/bash", "-c", "cd /fgt-workspace ; npm run switch-to-test-chain ; npm run server & ( sleep 5s ; npm run build-all ; tail -f /dev/null )"]

networks:
  qbn-net:
    name: qbn-net
    external: true
