version: "2.3"
x-participant-def:
  &participant-def
  restart: "unless-stopped"
  build:
    context: ../docker/api
  entrypoint: ["/bin/sh", "-c"]
  ports:
    - "8080:8080"
    - "8081:8081"
x-mah-def:
  &mah-def
  << : *participant-def
  command:
    - |
      npm run build-all
      npm run run-mah
  depends_on:
    fgt-workspace:
      condition: service_healthy
x-whs-def:
  &whs-def
  << : *participant-def
  command:
    - |
      npm run build-all
      npm run run-whs
  depends_on:
    mah-roche:
      condition: service_healthy
x-pha-def:
  &pha-def
  << : *participant-def
  command:
    - |
      npm run build-all
      npm run run-pha
  depends_on:
    whs-takeda :
      condition: service_healthy
services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.priority=2"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "8080:8080"
    networks:
      - traceability-net
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.priority=2"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - traceability-net
  fgt-workspace:
    container_name: fgt-workspace
    build:
      context: ../api/traceability
    hostname: fgt-workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traceability.rule=PathPrefix(`/`)"
      - "traefik.http.routers.traceability.priority=1"
#      - "traefik.http.routers.traceability.rule=HostRegexp(`fgt(:?\\-(?:dev|tst))?\\.pharmaledger\\.pdmfc\\.com`)"
      - "traefik.http.routers.traceability.entrypoints=web"
#      - "traefik.http.middlewares.traceability.stripprefix.prefixes=/traceability"
#      - "traefik.http.middlewares.traceability.stripprefix.forceSlash=false"
#      - "traefik.http.routers.traceability.middlewares=traceability@docker"
    volumes:
      - traceability_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      - traceability-net
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8080/dsu-explorer/wallet-patch/seed" ]
#      interval: 5s
#      timeout: 3s
#      retries: 20
#      start_period: 5s
#  mah-roche:
#    << : *mah-def
#    container_name: mah-roche
#    hostname: mah-roche
#    ports:
#      - "8080:8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.traceability.rule=(HostRegexp(`fgt(:?\-(?:dev|tst))?\.pharmaledger\.pdmfc\.com`) && PathPrefix(`/mah-roche/`))"
#      - "traefik.http.routers.traceability.entrypoints=web"
#    volumes:
#      - mah-roche_vol:/fgt-workspace/apihub-root/external-volume
#    networks:
#      traceability-net:
#        ipv4_address: 172.16.63.10
#    env_file:
#      - ../docker/api/env/mah-roche.env
#    environment:
#      - ROLE=MAH
#  mhs-takeda:
#    <<: *whs-def
#    container_name: whs-takeda
#    hostname: whs-takeda
#    ports:
#      - "8080:8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.traceability.rule=(HostRegexp(`fgt(:?\-(?:dev|tst))?\.pharmaledger\.pdmfc\.com`) && PathPrefix(`/whs-takeda/`))"
#      - "traefik.http.routers.traceability.entrypoints=web"
#    volumes:
#      - whs-takeda_vol:/fgt-workspace/apihub-root/external-volume
#    networks:
#      traceability-net:
#        ipv4_address: 172.16.63.51
#    env_file:
#      - ../docker/api/env/whs-takeda.env
#    environment:
#      - ROLE=WHS
#  pha-1:
#    <<: *pha-def
#    container_name: pha-1
#    hostname: pha-1
#    ports:
#      - "8080:8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.traceability.rule=(HostRegexp(`fgt(:?\-(?:dev|tst))?\.pharmaledger\.pdmfc\.com`) && PathPrefix(`/pha-1/`))"
#      - "traefik.http.routers.traceability.entrypoints=web"
#    volumes:
#      - pha-1_vol:/fgt-workspace/apihub-root/external-volume
#    networks:
#      traceability-net:
#        ipv4_address: 172.16.63.71
#    env_file:
#      - ../docker/api/env/pha-1.env
#    environment:
#      - ROLE=PHA
networks:
  traceability-net:
    name: traceability-net
    driver: bridge
volumes:
  "traceability_vol":
#  "mah-roche_vol":
#  "whs-takeda_vol":
#  "pha-1_vol":