version: "2.3"
x-participant-def:
  &participant-def
  restart: "unless-stopped"
#  ports:
#    - "8080:8080"
#    - "8081:8081"
#    - "8082:3009"
x-mah-def:
  &mah-def
  << : *participant-def
#  depends_on:
#    fgt-workspace:
#      condition: service_healthy
x-whs-def:
  &whs-def
  << : *participant-def
#  depends_on:
#    mah-roche:
#      condition: service_healthy
x-pha-def:
  &pha-def
  << : *participant-def
#  depends_on:
#    whs-takeda :
#      condition: service_healthy
services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.priority=2"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "8080:8080"
    networks:
      - traceability-net

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.priority=2"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - traceability-net

  fgt-workspace:
    container_name: fgt-workspace
    build:
      context: ../api/traceability
    hostname: fgt-workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traceability.rule=Host(`traceability.localhost`)"
#      - "traefik.http.routers.traceability.rule=PathPrefix(`/`)"
      - "traefik.http.routers.traceability.priority=1"
#      - "traefik.http.routers.traceability.rule=HostRegexp(`fgt(:?\\-(?:dev|tst|local))?\\.pharmaledger\\.pdmfc\\.com`)"
      - "traefik.http.routers.traceability.entrypoints=web"
#      - "traefik.http.middlewares.traceability.stripprefix.prefixes=/traceability"
#      - "traefik.http.middlewares.traceability.stripprefix.forceSlash=false"
#      - "traefik.http.routers.traceability.middlewares=traceability@docker"
    volumes:
      - traceability_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      - traceability-net

  mah-roche:
    << : *mah-def
    container_name: mah-roche
    hostname: mah-roche
    build:
      context: ../api
      args:
        ROLE: mah
        CREDENTIALS_FILE: mah-roche.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mah-roche.rule=Host(`mah-roche.localhost`)"
      - "traefik.http.routers.mah-roche.entrypoints=web"

#      - "traefik.http.routers.mah-roche-api.rule=Host(`mah-roche.localhost`) && PathPrefix(`/api`)"
#      - "traefik.http.routers.mah-roche-api.entrypoints=web"
#      - "traefik.http.services.mah-roche-api.loadbalancer.server.port=8081"
#      - "traefik.http.services.mah-roche-api.loadbalancer.sticky=true"
#
      - "traefik.http.routers.mah-roche-swagger.rule=Host(`mah-roche.localhost`) && PathPrefix(`/swagger`)"
      - "traefik.http.routers.mah-roche-swagger.entrypoints=web"
      - "traefik.http.middlewares.mah-roche-swagger.stripprefix.prefixes=/swagger"
      - "traefik.http.middlewares.mah-roche-swagger.stripprefix.forceSlash=false"
      - "traefik.http.routers.mah-roche-swagger.middlewares=mah-roche-swagger@docker"
      - "traefik.http.services.mah-roche-swagger.loadbalancer.server.port=3009"
    volumes:
      - mah-roche_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      - traceability-net

#  mhs-takeda:
#    <<: *whs-def
#    container_name: whs-takeda
#    hostname: whs-takeda
#    ports:
#      - "8080:8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.traceability.rule=(HostRegexp(`fgt(:?\-(?:dev|tst))?\.pharmaledger\.pdmfc\.com`) && PathPrefix(`/whs-takeda/`))"
#      - "traefik.http.routers.traceability.entrypoints=web"
#    volumes:
#      - whs-takeda_vol:/fgt-workspace/apihub-root/external-volume
#    networks:
#      traceability-net:
#        ipv4_address: 172.16.63.51
#    env_file:
#      - ../docker/api/env/whs-takeda.env
#    environment:
#      - ROLE=WHS
#  pha-1:
#    <<: *pha-def
#    container_name: pha-1
#    hostname: pha-1
#    ports:
#      - "8080:8080"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.traceability.rule=(HostRegexp(`fgt(:?\-(?:dev|tst))?\.pharmaledger\.pdmfc\.com`) && PathPrefix(`/pha-1/`))"
#      - "traefik.http.routers.traceability.entrypoints=web"
#    volumes:
#      - pha-1_vol:/fgt-workspace/apihub-root/external-volume
#    networks:
#      traceability-net:
#        ipv4_address: 172.16.63.71
#    env_file:
#      - ../docker/api/env/pha-1.env
#    environment:
#      - ROLE=PHA
networks:
  traceability-net:
    name: traceability-net
    driver: bridge
volumes:
  "traceability_vol":
  "mah-roche_vol":
#  "whs-takeda_vol":
#  "pha-1_vol":