version: "2.3"
x-participant-def:
  &participant-def
  restart: "unless-stopped"
#  ports:
#    - "8080:8080"
#    - "8081:8081"
#    - "8082:3009"
x-mah-def:
  &mah-def
  << : *participant-def
#  depends_on:
#    fgt-workspace:
#      condition: service_healthy
x-whs-def:
  &whs-def
  << : *participant-def
#  depends_on:
#    mah-roche:
#      condition: service_healthy
x-pha-def:
  &pha-def
  << : *participant-def
#  depends_on:
#    whs-takeda :
#      condition: service_healthy
services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "8080:8080"
    networks:
      - traceability-net

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - traceability-net

  fgt-workspace:
    container_name: fgt-workspace
    build:
      context: ../api/traceability
    hostname: fgt-workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traceability.rule=Host(`traceability.localhost`)"
      - "traefik.http.middlewares.traceability-headers.headers.accessControlAllowOriginListRegex=.*?"
      - "traefik.http.middlewares.traceability-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT"
      - "traefik.http.middlewares.traceability-headers.headers.accessControlAllowHeaders=content-type,x-content-length"
      - "traefik.http.middlewares.traceability-headers.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.traceability-headers.headers.addVaryHeader=true"
      - "traefik.http.routers.traceability.middlewares=traceability-headers"
      - "traefik.http.services.traceability.loadbalancer.server.port=8080"
      - "traefik.http.routers.traceability.entrypoints=web"
    volumes:
      - traceability_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      traceability-net:
        ipv4_address: 172.16.63.51

  mah-roche:
    << : *mah-def
    container_name: mah-roche
    hostname: mah-roche
    build:
      context: ../api
      args:
        ROLE: mah
        WALLET: mah
        CREDENTIALS_FILE: mah-roche.json
        SWAGGER_SERVER: http://api.mah-roche.localhost:8080/traceability
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mah-roche.rule=Host(`mah-roche.localhost`)"
      - "traefik.http.middlewares.mah-roche-headers.headers.accessControlAllowOriginListRegex=.*?"
      - "traefik.http.middlewares.mah-roche-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT"
      - "traefik.http.middlewares.mah-roche-headers.headers.accessControlAllowHeaders=content-type,x-content-length"
      - "traefik.http.middlewares.mah-roche-headers.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.mah-roche-headers.headers.addVaryHeader=true"
      - "traefik.http.routers.mah-roche.middlewares=mah-roche-headers"
      - "traefik.http.routers.mah-roche.entrypoints=web"
      - "traefik.http.routers.mah-roche.service=mah-roche"
      - "traefik.http.services.mah-roche.loadbalancer.server.port=8080"

      - "traefik.http.routers.mah-roche-swagger.rule=Host(`swagger.mah-roche.localhost`)"
      - "traefik.http.routers.mah-roche-swagger.entrypoints=web"
      - "traefik.http.routers.mah-roche-swagger.service=mah-roche-swagger"
      - "traefik.http.services.mah-roche-swagger.loadbalancer.server.port=3009"

      - "traefik.http.routers.mah-roche-api.rule=Host(`api.mah-roche.localhost`)"
      - "traefik.http.routers.mah-roche-api.entrypoints=web"
      - "traefik.http.routers.mah-roche-api.service=mah-roche-api"
      - "traefik.http.services.mah-roche-api.loadbalancer.server.port=8081"
    volumes:
      - mah-roche_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      traceability-net:
        ipv4_address: 172.16.63.61

  whs-1:
    << : *whs-def
    container_name: whs1
    hostname: whs1
    build:
      context: ../api
      args:
        ROLE: whs
        WALLET: wholesaler
        CREDENTIALS_FILE: whs-1.json
        SWAGGER_SERVER: http://api.whs1.localhost:8080/traceability
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.whs1.rule=Host(`whs1.localhost`)"
      - "traefik.http.middlewares.whs1-headers.headers.accessControlAllowOriginListRegex=.*?"
      - "traefik.http.middlewares.whs1-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT"
      - "traefik.http.middlewares.whs1-headers.headers.accessControlAllowHeaders=content-type,x-content-length"
      - "traefik.http.middlewares.whs1-headers.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.whs1-headers.headers.addVaryHeader=true"
      - "traefik.http.routers.whs1.middlewares=whs1-headers"
      - "traefik.http.routers.whs1.entrypoints=web"
      - "traefik.http.routers.whs1.service=whs1"
      - "traefik.http.services.whs1.loadbalancer.server.port=8080"

      - "traefik.http.routers.whs1-swagger.rule=Host(`swagger.whs1.localhost`)"
      - "traefik.http.routers.whs1-swagger.entrypoints=web"
      - "traefik.http.routers.whs1-swagger.service=whs1-swagger"
      - "traefik.http.services.whs1-swagger.loadbalancer.server.port=3009"

      - "traefik.http.routers.whs1-api.rule=Host(`api.whs1.localhost`)"
      - "traefik.http.routers.whs1-api.entrypoints=web"
      - "traefik.http.routers.whs1-api.service=whs1-api"
      - "traefik.http.services.whs1-api.loadbalancer.server.port=3001"
    volumes:
      - whs1_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      - traceability-net

  pha-1:
    << : *pha-def
    container_name: pha1
    hostname: pha1
    build:
      context: ../api
      args:
        ROLE: pha
        WALLET: pharmacy
        CREDENTIALS_FILE: pha-1.json
        SWAGGER_SERVER: http://api.pha1.localhost:8080/traceability
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.pha1.rule=Host(`pha1.localhost`)"
      - "traefik.http.middlewares.pha1-headers.headers.accessControlAllowOriginListRegex=.*?"
      - "traefik.http.middlewares.pha1-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT"
      - "traefik.http.middlewares.pha1-headers.headers.accessControlAllowHeaders=content-type,x-content-length"
      - "traefik.http.middlewares.pha1-headers.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.pha1-headers.headers.addVaryHeader=true"
      - "traefik.http.routers.pha1.middlewares=pha1-headers"
      - "traefik.http.routers.pha1.entrypoints=web"
      - "traefik.http.routers.pha1.service=pha1"
      - "traefik.http.services.pha1.loadbalancer.server.port=8080"

      - "traefik.http.routers.pha1-swagger.rule=Host(`swagger.pha1.localhost`)"
      - "traefik.http.routers.pha1-swagger.entrypoints=web"
      - "traefik.http.routers.pha1-swagger.service=pha1-swagger"
      - "traefik.http.services.pha1-swagger.loadbalancer.server.port=3009"

      - "traefik.http.routers.pha1-api.rule=Host(`api.pha1.localhost`)"
      - "traefik.http.routers.pha1-api.entrypoints=web"
      - "traefik.http.routers.pha1-api.service=pha1-api"
      - "traefik.http.services.pha1-api.loadbalancer.server.port=3002"
    volumes:
      - pha1_vol:/fgt-workspace/apihub-root/external-volume
    networks:
      - traceability-net
networks:
  traceability-net:
    name: traceability-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.63.0/24
volumes:
  "traceability_vol":
  "mah-roche_vol":
  "whs1_vol":
  "pha1_vol":