# Requires a local docker image pharmaleger/fgt built.
# Can be built with minikube_build.sh or similar
apiVersion: v1
kind: Pod
metadata:
  name: fgt
  labels:
    app: fgt
spec:
  containers:
  - name: fgt
    image: pharmaledger/fgt
    imagePullPolicy: Never
    command: ["/bin/sh", "-c"]
    args: ["echo Hello ; cd /fgt-workspace ; npm run server & ( sleep 1m ; npm run build-all ; npm run environment-test ; tail -f /dev/null)"]
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fgt-endpoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: fgt
  ports:
  - port: 8080
    targetPort: 8080